apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-management
  labels:
    app: hospital-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-management
  template:
    metadata:
      labels:
        app: hospital-management
    spec:
      containers:
      - name: hospital-management
        image: aniketharugade09/hospital-management-service:latest
        ports:
        - containerPort: 8080
