services:
  hospital-service:
 #   image: ${aniketharugade09}/hospital-management-service:${BUILD_NUMBER}
 
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
