version: '3'
services:
  hospital-service:
    image: ${DOCKER_USERNAME}/hospital-management-service:46
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
