apiVersion: v1
kind: Service
metadata:
  name: hospital-management-service
spec:
  type: NodePort
  selector:
    app: hospital-management
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
